### PR TITLE
elixir 1.1.0 is out

### PR DESCRIPTION
**Pull request by tverlaan**
All tests passed. Can you merge this so I won't see the compile-time warning every time :-)

```
 mix test
Compiled lib/apex.ex
Compiled lib/apex/format/color.ex
Compiled lib/apex/format/utils.ex
Compiled lib/apex/format/seq.ex
Compiled lib/apex/awesome_def.ex
Compiled lib/apex/format/tuple.ex
Compiled lib/apex/format.ex
Generated apex app

Apex.Format.Utils.Test
  * #indent (0.00ms)
  * #next_indent_level (0.00ms)
  * #separator_line (1.4ms)
  * #colorize should color when it's asked for it (1.3ms)
  * #colorize should not do anything when it's turned off (0.00ms)

Apex.Format.Test
  * Can format function (1.0ms)
  * Can format a list of strings (0.1ms)
  * Can format HashSets (0.07ms)
  * Can format ranges (0.04ms)
  * Can format pid (0.7ms)
  * Can format integers (0.01ms)
  * Can format tuples that don't start with an atom (0.06ms)
  * Can format Dicts (0.06ms)
  * Can format empty tuples (0.00ms)
  * Can format atoms (0.03ms)
  * Can format keyword list (0.08ms)
  * Can format structs (2.5ms)
  * Can format floats (0.01ms)
  * Can format references (1.0ms)
  * Can format Maps (0.08ms)
  * Can format records (0.05ms)
  * Can format a list containing a list (0.08ms)


Finished in 0.1 seconds (0.1s on load, 0.01s on tests)
22 tests, 0 failures
```

### CODE REVIEW

**Comment by BjRo** [comment]
Klaro :0

**Comment by BjRo** [comment]
When elixir 1.1.0 is available via homebrew, I'll push the new package.

**Comment by BjRo** [comment]
The package is on hex

**Comment by tverlaan** [comment]
Thanks!

**Pull request merged**
