### PR TITLE
true, false and nil are special

### PR DESCRIPTION
**Pull request by bsanyi**
These are tiny tweaks mostly around true, false and nil. Tuples with these special atoms as their first tag are also printed differently.  In addition I think empty lists and maps should be printed simply as [] and %{} on a single line.

### CODE REVIEW

**Comment by BjRo** [comment]
I checked out the branch and on my machine the tests are not all green for your branch. Can you please take a look?

**Comment by bsanyi** [comment]
This is because of the new atom format.  I switched to the format `:atom` instead of the simple `atom` format except when the atom is true, false or nil.  I adjusted the test to the new format.

**Comment by BjRo** [comment]
Cool, thank you!

**Comment by BjRo** [comment]
`0.5.2` pushed to `hex.pm`

**Pull request merged**
