### PR TITLE
Customisable colours

### PR DESCRIPTION
**Pull request by BjRo**
Hey @pstare, 

can you take a look at this. I took a stab at implementing the feature. You can now tweak colors with a `~/.apexrc` file and the result gets compiled into your version of the `Apex` package.

Could you take a look and see whether this works for you?

Cheerio
Björn

### CODE REVIEW

**Comment by pstare** [comment]
@BjRo This works great. Just two comments:

1. The documentation should really emphasize that this is a compile time operation. I made a couple of changes that were reflected, but spent a while scratching my head wondering why the other changes were not. It's because the dependency had already been compiled. I ran `mix deps.compile` until the cows came home, but it wouldn't recompile apex because it doesn't recognize the `.apexrc` file as a dependency. Is there any way to cause it to do a recompile when this file is modified? Failing that, the docs should state that the user should:

```elixir
mix deps.compile apex
```

2. Is there any way to make this a run-time dependency, not a compile-time one? Feel free to educate me here, I'm new to elixir and it seems all the metaprogramming is done with macros. However, we should still be able to provide config values without having to recompile the app, no? 

3. It might be useful to resolve `.apexrc` in the home directory, and then apply a mix project-specific one on top of that. I don't have use for this, others might (though this is pretty low on a laundry list of desires).

4. Is this standard practice for configuring Elixir libraries? Having a dotfile that is essentially an Elixir map? I know José is pretty anti-yaml, so just wondering.

By the way, this is my .apexrc for now:

```elixir
%{
  colors: %{
    binary:   [IO.ANSI.color(187), :normal],
    true:     [IO.ANSI.color(201), :normal],
    false:    [IO.ANSI.color(198), :normal],
    atom:     [IO.ANSI.color(133), :normal],
    float:    [IO.ANSI.color(80), :normal],
    integer:  [IO.ANSI.color(80), :normal],
    function: [IO.ANSI.color(162), :normal]
  }
}
```

**Comment by BjRo** [comment]
Hey @pstare,

thank you for checking it out. Let me try to answer you comments

1. Why make it not a runtime dependency? When I you want to manage state inside an erlang application you usually have to do this via processes. Processes though would need to be started and supervised and require some additional changes to make them work. `apex` would then need to be an application and manage a supervision tree. I wondered then, how often do we actually change the colors in an app. I don't really think we do this often. Probably only for figuring out the colors initially. That's how I came to the conclusion that this might be a good compile time task. I agree that changing the documentation to emphasis this makes totally sense. I think you can also specify a file as a compiletime dependency in elixir (which forces re-compilation when the file changes, but I have to research there)

2. The dotfile approach is unusual. Usually you configure elixir 'things' via the elixir configuration system. However this is then per project. I thought it might be a good idea to do it the way I did, because then the apex settings are easily the same across multiple elixir projects that use `apex` and spares a user from needing to set it up in every project again and again.

3. I just took an Elixir datastructure as the configuration format of the `.apexrc` because that was pretty easy to instrument in the macros. Erlang configuration often is also done in Erlang terms, so I would say it's not untypical.

While I was writing this I also realized that there's an option also to extend this by managing runtime-changable colors via `Application.get_env` and resolving the target color with

```elixir
color_from_apexrc(key) || color_from_app_config(key) || default_color(key)
```

I think this would give you best of all worlds and would also allow you to tinker with the colors at runtime. 

What do you think? Does this make sense?

**Comment by pstare** [comment]
I haven't had time to try this yet but the cascade you mention sounds perfect!

**Comment by BjRo** [comment]
I've implemented and documented the cascade. When you've got the time, please test whether this works out for you. I can release a new version shortly after

**Comment by BjRo** [comment]
Merged via 950d405

**Comment by BjRo** [comment]
Released with `0.6.0`

**Comment by pstare** [comment]
@BjRo this works for me but you may want to point out that `mix deps.compile apex` will not recompile/pick up `.apexrc` changes, regardless of file modification date (because strictly speaking that file is not part of the project and exists in the current user's home directory). So in order to pick up any changes there, the user needs to do a `mix deps.compile --force apex`

Thanks for doing this, by the way!

**Pull request closed without merging**
